title: Kevin Wang's Website
description: Welcome to my personal website!
theme: just-the-docs

url: https://kevinwyk888.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
